
name: Package_Upload

on:
  pull_request:
    branches: [ pull-request-upload-artifact-test  ]
  
  #push:
    #branches: [ AWIBOF-6460-build-package-test ]

  workflow_dispatch:
    inputs:
       logLevel:
          description: 'Log level'     
          required: true
          default: 'warning'
       tags:
          description: 'Test scenario tags'

jobs:
  Upload_Package:
    runs-on: VM
    env:
      SHA7: ${GITHUB_SHA::7}
    steps:
    - run: |
        sudo chown -R $USER:$USER $GITHUB_WORKSPACE

    - uses: actions/checkout@v1

    - name: Build Setup
      working-directory: ${{github.workspace}}
      run: |
        sudo apt update
        chmod +x .github/workflows/script/build_setup.sh
        .github/workflows/script/build_setup.sh -r ${{github.sha}} -d ${{github.workspace}} -c --with-fpic

    - name: package build
      working-directory: ${{github.workspace}}
      run: |
        sudo make package -j8

    - name: Package artifacts
      uses: actions/upload-artifact@v3
      with:
        name: poseidonos-$SHA7.deb
        path: |
          ${{github.workspace}}/package/debian/poseidonos.deb
